version: '3.1'
services:
  db:
    container_name: db-banking-api
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banking-api
    ports:
      - "5432:5432"
